name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: npm install
        working-directory: ./Back-end

      # Remove or comment out the test step if not needed
      # - name: Run backend tests
      #   run: npm test
      #   working-directory: ./Back-end

  docker-build:
    runs-on: ubuntu-latest
    needs: backend-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build
